sonar.projectKey=task-tracking-app
sonar.projectName=Task Tracking App
sonar.sources=backend/app,frontend/src,infra,k8s,monitoring,argocd
sonar.exclusions=**/node_modules/**,**/.terraform/**,**/dist/**
sonar.python.version=3.12
