sonar.projectKey=task-tracking-infrastructure
sonar.projectName=Task Tracking Infrastructure
sonar.sources=.
sonar.sourceEncoding=UTF-8
sonar.exclusions=**/.terraform/**,**/tfplan,**/*.tfstate,**/*.tfstate.*,**/*.sarif
